---
##############################################
#  Valeriy Solovyov <weldpua2008@gmail.com>
##############################################
 - name: ensure required packages are installed for Oracle Java
   apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
   with_items:
     - python-software-properties


 - name: Add Oracle Java repository to sources
   apt_repository: repo='ppa:webupd8team/java' state=present update_cache=yes

 - name: Autoaccept license for Oracle Java
   action: shell echo oracle-java{{ oraclejdk_version }}-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
   changed_when: false

# - name: Update APT package cache
#   action: apt update_cache=yes
#   when: apt_state == 'present'

 - name: Install Oracle Java
   action: apt pkg=oracle-java{{ oraclejdk_version }}-installer state=present

 - name: Set Java Env
   action: apt pkg=oracle-java{{ oraclejdk_version }}-set-default state=present
