- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - java
    - jdk


- include: install-jdk-debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - java
    - jdk


- include: install-jdk-redhat.yml
#  when: "ansible_os_family == 'Debian'"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
  tags:
    - java
    - jdk

#
#- include: install-fedora.yml
#  when: ansible_distribution == "Fedora"
#  tags:
#    - java
#
#- include: install-suse.yml
#  when: ansible_os_family == 'Suse' or ansible_distribution == 'SLES' or ansible_distribution == 'OES' or ansible_distribution == 'Suse' or ansible_distribution == 'openSUSE'
##  when: ansible_distribution == 'SLES' or ansible_distribution == 'OES' or ansible_distribution == 'Suse' or ansible_distribution == 'openSUSE'
#  tags:
#    - java
#
- include: install-jdk-freebsd.yml
  when: ansible_os_family == 'FreeBSD'
  tags:
    - java
    - jdk

- include: install-jdk-gentoo.yml
  when: ansible_os_family == 'Gentoo '
  tags:
    - java
    - jdk

- name: set JAVA_HOME...
  template: src=java.sh.j2 dest='/etc/profile.d/java.sh' mode=644
  tags:
    - java
    - jdk
