# Setup for Vagrant
- fail: msg="Please define  oraclejava_version or openjdk_version"
  when: openjdk_version is not defined and oraclejava_version is not defined
  tags:
    - java
    - oracle-java
    - openjdk

- set_fact:
    java_type="jdk"
  when: oraclejava_version is defined
  tags:
    - java
    - oracle-java

- set_fact:
    java_type="openjdk"
  when: openjdk_version is defined
  tags:
    - java
    - openjdk

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - java
    - oracle-java
    - openjdk

- include: install-openjdk-debian.yml
  when: ansible_os_family == 'Debian' and java_type == 'openjdk'
  tags:
    - java
    - openjdk

- include: install-jdk-debian.yml
  when: ansible_os_family == 'Debian' and java_type == 'jdk'
  tags:
    - java
    - oracle-java

- include: install-openjdk-redhat.yml
#  when: "ansible_os_family == 'Debian'"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'  and java_type == 'openjdk'
  tags:
    - java
    - openjdk

- include: install-jdk-redhat.yml
#  when: "ansible_os_family == 'Debian'"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'  and java_type == 'jdk'
  tags:
    - java
    - oracle-java

#
#- include: install-fedora.yml
#  when: ansible_distribution == "Fedora"
#  tags:
#    - java
#
#- include: install-suse.yml
#  when: ansible_os_family == 'Suse' or ansible_distribution == 'SLES' or ansible_distribution == 'OES' or ansible_distribution == 'Suse' or ansible_distribution == 'openSUSE'
##  when: ansible_distribution == 'SLES' or ansible_distribution == 'OES' or ansible_distribution == 'Suse' or ansible_distribution == 'openSUSE'
#  tags:
#    - java
#
- include: install-freebsd.yml
  when: ansible_os_family == 'FreeBSD'
  tags:
    - java
    - oracle-java
    - openjdk

- include: install-openjdk-gentoo.yml
  when: ansible_os_family == 'Gentoo '  and java_type == 'openjdk'
  tags:
    - java
    - oracle-java

- name: set JAVA_HOME...
  template: src=java.sh.j2 dest='/etc/profile.d/java.sh' mode=644
  tags:
    - java
    - oracle-java
    - openjdk
